require 'railsless-deploy'
load '../common.rb'

set :application, 'proxy'
set :scm, :git
set :repository,  "http://github.com/bpaquet/offline-proxy.git"
server "storage.perf", :app, :web, :db, :primary => true
set :user, "deploy"
set :deploy_to, '/apps/cw_offline_proxy/'
set :repository_for_local_deployment, '../../../../infra/proxy'
set :ssh_options, { :forward_agent => true }

set :link_dir, {
  '/storage' => '/storage',
}

set :default_environment, env_http_proxy


task :node_init, :roles => :app do
  run "/home/deploy/.nvm/nvm.sh && nvm use 0.8", :env => env_http_proxy
end

task :restart, :roles => :app do
  run "/etc/init.d/#{application} restart"
end

#after 'deploy:finalize_update', 'node_init'

after 'deploy', 'restart'

task :cleanup do
  top.deploy.cleanup
end
