
        # -*- mode: ruby -*-
        # vi: set ft=ruby :
        Vagrant::Config.run do |config|
          config.vm.box ="precise64"
          config.vm.network :hostonly, "192.168.56.7"
          config.vm.host_name = "dev.perf"
          config.vm.customize ["modifyvm", :id, "--memory", 1024]
        end
        